background #0f1417
foreground #dfe3e7

selection_background #004d67
selection_foreground #c1e8ff

cursor #8dcff2
cursor_text_color #003548

url_color #8dcff2

active_border_color #8dcff2
inactive_border_color #40484c
bell_border_color #ffb4ab

active_tab_background #8dcff2
active_tab_foreground #003548
inactive_tab_background #40484c
inactive_tab_foreground #c0c7cd
